db.url = jdbc:mysql://localhost:3306/banking
dbt.url = jdbc:mysql://localhost:3306/bankingTest
db.name = root
db.password = MasokoBums

# hikari config

hikari.maximumPoolSize = 10
hikari.minimumIdle = 2
hikari.idleTimeout = 60000
hikari.connectionTimeout = 30000